Repository prgrms-be-devcourse/NBE4-5-3-Team09, pull requests merged in 2025-04, with the labels that each got.

#5 Feat/4 user migration
  backend/build.gradle
  backend/build.gradle.kts
  backend/src/main/java/com/coing/CoingApplication.java
  backend/src/main/java/com/coing/CoingApplication.kt
  backend/src/main/java/com/coing/domain/chat/controller/ChatWebSocketController.java
  backend/src/main/java/com/coing/domain/chat/controller/ChatWebSocketController.kt
  backend/src/main/java/com/coing/domain/chat/dto/ChatMessageDto.java
  backend/src/main/java/com/coing/domain/chat/dto/ChatMessageDto.kt
  backend/src/main/java/com/coing/domain/chat/entity/ChatMessage.java
  backend/src/main/java/com/coing/domain/chat/entity/ChatMessage.kt
  backend/src/main/java/com/coing/domain/chat/entity/ChatRoom.java
  backend/src/main/java/com/coing/domain/chat/entity/ChatRoom.kt
  backend/src/main/java/com/coing/domain/chat/handler/ChatWebSocketHandler.java
  backend/src/main/java/com/coing/domain/chat/handler/ChatWebSocketHandler.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatHelperService.java
  backend/src/main/java/com/coing/domain/chat/service/ChatService.java
  backend/src/main/java/com/coing/domain/chat/service/ChatService.kt
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/UserController.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/EmailVerificationResponse.java
  backend/src/main/java/com/coing/domain/user/controller/dto/EmailVerificationResponse.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/PasswordResetConfirmRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/PasswordResetConfirmRequest.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/PasswordResetRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/PasswordResetRequest.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/SignOutRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/SignOutRequest.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/UserLoginRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserLoginRequest.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/UserLogoutRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserLogoutRequest.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/UserResponse.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserResponse.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/UserSignUpRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserSignUpRequest.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/UserSignupResponse.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserSignupResponse.kt
  backend/src/main/java/com/coing/domain/user/email/service/EmailVerificationService.java
  backend/src/main/java/com/coing/domain/user/email/service/EmailVerificationService.kt
  backend/src/main/java/com/coing/domain/user/entity/User.java
  backend/src/main/java/com/coing/domain/user/entity/User.kt
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.kt
  backend/src/main/java/com/coing/domain/user/service/OAuth2UserService.java
  backend/src/main/java/com/coing/domain/user/service/OAuth2UserService.kt
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/domain/user/service/UserService.kt
  backend/src/main/java/com/coing/global/annotation/NoArg.kt
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.kt
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.java
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.kt
Labels: BE, ✨ feature

#1 Feat/201 social login
  backend/src/main/java/com/coing/domain/user/controller/UserController.kt
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.kt
  backend/src/main/java/com/coing/global/config/CacheConfig.java
  backend/src/main/java/com/coing/global/security/handler/OAuth2LoginSuccessHandler.java
  frontend/src/app/user/social-login/callback/page.tsx
  frontend/src/app/user/social-login/redirect/page.tsx
Labels: BE, ✨ feature

#9 Feat/6 ticker migration
  api_schema.json
  backend/build.gradle.kts
  backend/src/main/java/com/coing/domain/coin/market/dto/MarketDto.java
  backend/src/main/java/com/coing/domain/coin/market/entity/Market.java
  backend/src/main/java/com/coing/domain/coin/market/entity/Market.kt
  backend/src/main/java/com/coing/domain/coin/ticker/TickerController.java
  backend/src/main/java/com/coing/domain/coin/ticker/TickerController.kt
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickerDto.java
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickerDto.kt
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickerResponse.java
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickerResponse.kt
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickersRequest.java
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickersRequest.kt
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickersResponse.java
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickersResponse.kt
  backend/src/main/java/com/coing/domain/coin/ticker/entity/Ticker.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/Ticker.kt
  backend/src/main/java/com/coing/domain/coin/ticker/entity/enums/MarketState.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/enums/MarketState.kt
  backend/src/main/java/com/coing/domain/coin/ticker/entity/enums/MarketWarning.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/enums/MarketWarning.kt
  backend/src/main/java/com/coing/domain/coin/ticker/service/TickerService.java
  backend/src/main/java/com/coing/domain/coin/ticker/service/TickerService.kt
  backend/src/main/java/com/coing/global/config/JacksonConfig.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTickerDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTickerDto.kt
  backend/src/test/java/com/coing/domain/coin/ticker/service/TickerServiceTest.java
  backend/src/test/java/com/coing/domain/coin/ticker/service/TickerServiceTest.kt
Labels: BE, ✨ feature

#11 Feat/10 trade migration
  api_schema.json
  backend/src/main/java/com/coing/domain/coin/trade/TradeController.java
  backend/src/main/java/com/coing/domain/coin/trade/TradeController.kt
  backend/src/main/java/com/coing/domain/coin/trade/dto/TradeDto.java
  backend/src/main/java/com/coing/domain/coin/trade/dto/TradeDto.kt
  backend/src/main/java/com/coing/domain/coin/trade/dto/TradeResponse.java
  backend/src/main/java/com/coing/domain/coin/trade/dto/TradeResponse.kt
  backend/src/main/java/com/coing/domain/coin/trade/entity/Trade.java
  backend/src/main/java/com/coing/domain/coin/trade/entity/Trade.kt
  backend/src/main/java/com/coing/domain/coin/trade/service/TradeService.java
  backend/src/main/java/com/coing/domain/coin/trade/service/TradeService.kt
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTradeDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTradeDto.kt
  backend/src/test/java/com/coing/domain/coin/trade/service/TradeServiceTest.java
  backend/src/test/java/com/coing/domain/coin/trade/service/TradeServiceTest.kt
Labels: BE, ✨ feature

#18 Feat/7 chat migration
  backend/build.gradle.kts
  backend/src/main/java/com/coing/domain/chat/controller/ChatController.java
  backend/src/main/java/com/coing/domain/chat/controller/ChatController.kt
  backend/src/main/java/com/coing/domain/chat/entity/ChatMessage.kt
  backend/src/main/java/com/coing/domain/chat/entity/ChatRoom.kt
  backend/src/main/java/com/coing/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/coing/domain/chat/repository/ChatMessageRepository.kt
  backend/src/main/java/com/coing/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/coing/domain/chat/repository/ChatRoomRepository.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatHelperService.java
  backend/src/main/java/com/coing/domain/chat/service/ChatHelperService.kt
  backend/src/main/java/com/coing/domain/user/dto/CustomOAuth2User.java
  backend/src/main/java/com/coing/domain/user/dto/CustomOAuth2User.kt
  backend/src/main/java/com/coing/domain/user/email/service/EmailSenderService.java
  backend/src/main/java/com/coing/domain/user/email/service/EmailSenderService.kt
  backend/src/main/java/com/coing/domain/user/email/service/PasswordResetService.java
  backend/src/main/java/com/coing/domain/user/email/service/PasswordResetService.kt
  backend/src/main/java/com/coing/domain/user/repository/UserRepository.java
  backend/src/main/java/com/coing/domain/user/repository/UserRepository.kt
  backend/src/test/java/com/coing/domain/chat/controller/ChatControllerTest.kt
  backend/src/test/java/com/coing/domain/chat/service/ChatServiceTest.kt
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.kt
Labels: BE, ✨ feature

#21 Feat/14 kotlin migration - coin orderbook package
  backend/build.gradle.kts
  backend/src/main/java/com/coing/domain/coin/orderbook/dto/OrderbookDto.java
  backend/src/main/java/com/coing/domain/coin/orderbook/dto/OrderbookDto.kt
  backend/src/main/java/com/coing/domain/coin/orderbook/entity/Orderbook.java
  backend/src/main/java/com/coing/domain/coin/orderbook/entity/Orderbook.kt
  backend/src/main/java/com/coing/domain/coin/orderbook/entity/OrderbookUnit.java
  backend/src/main/java/com/coing/domain/coin/orderbook/entity/OrderbookUnit.kt
  backend/src/main/java/com/coing/domain/coin/orderbook/service/OrderbookService.java
  backend/src/main/java/com/coing/domain/coin/orderbook/service/OrderbookService.kt
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketOrderbookDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketOrderbookDto.kt
  backend/src/test/java/com/coing/domain/coin/orderbook/entity/OrderbookTest.java
  backend/src/test/java/com/coing/domain/coin/orderbook/entity/OrderbookTest.kt
  backend/src/test/java/com/coing/domain/coin/orderbook/service/OrderbookServiceTest.java
  backend/src/test/java/com/coing/domain/coin/orderbook/service/OrderbookServiceTest.kt
Labels: BE, ♻️ refactor

#22 Feat/8 market migration
  backend/build.gradle.kts
  backend/src/main/java/com/coing/domain/coin/market/controller/MarketController.java
  backend/src/main/java/com/coing/domain/coin/market/controller/MarketController.kt
  backend/src/main/java/com/coing/domain/coin/market/controller/dto/MarketResponse.java
  backend/src/main/java/com/coing/domain/coin/market/controller/dto/MarketResponse.kt
  backend/src/main/java/com/coing/domain/coin/market/dto/MarketDto.java
  backend/src/main/java/com/coing/domain/coin/market/dto/MarketDto.kt
  backend/src/main/java/com/coing/domain/coin/market/dto/MarketResponseDto.java
  backend/src/main/java/com/coing/domain/coin/market/dto/MarketResponseDto.kt
  backend/src/main/java/com/coing/domain/coin/market/entity/Market.kt
  backend/src/main/java/com/coing/domain/coin/market/repository/MarketRepository.java
  backend/src/main/java/com/coing/domain/coin/market/repository/MarketRepository.kt
  backend/src/main/java/com/coing/domain/coin/market/service/MarketCacheService.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketCacheService.kt
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.kt
  backend/src/main/java/com/coing/domain/news/service/NewsService.java
  backend/src/main/java/com/coing/domain/news/service/NewsService.kt
  backend/src/main/java/com/coing/domain/user/controller/UserController.kt
  backend/src/test/java/com/coing/domain/coin/market/service/MarketServiceTest.java
  backend/src/test/java/com/coing/domain/coin/market/service/MarketServiceTest.kt
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.kt
Labels: BE, ✨ feature

#23 Feat/20 coin candle migration
  backend/src/main/java/com/coing/domain/coin/candle/controller/CandleController.java
  backend/src/main/java/com/coing/domain/coin/candle/controller/CandleController.kt
  backend/src/main/java/com/coing/domain/coin/candle/dto/CandleDto.java
  backend/src/main/java/com/coing/domain/coin/candle/dto/CandleDto.kt
  backend/src/main/java/com/coing/domain/coin/candle/service/UpbitCandleService.java
  backend/src/main/java/com/coing/domain/coin/candle/service/UpbitCandleService.kt
  backend/src/test/java/com/coing/domain/coin/candle/controller/CandleControllerTest.kt
  backend/src/test/java/com/coing/domain/coin/candle/service/UpbitCandleServiceIntegrationTest.kt
  backend/src/test/java/com/coing/domain/coin/candle/service/UpbitCandleServiceTest.kt
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.kt
Labels: BE, ✨ feature

#25 Feat/19 news migration
  api_schema.json
  backend/src/main/java/com/coing/domain/bookmark/controller/BookmarkController.kt
  backend/src/main/java/com/coing/domain/bookmark/service/BookmarkService.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatService.kt
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.kt
  backend/src/main/java/com/coing/domain/news/controller/NewsController.java
  backend/src/main/java/com/coing/domain/news/controller/NewsController.kt
  backend/src/main/java/com/coing/domain/user/dto/CustomUserPrincipal.java
  backend/src/main/java/com/coing/domain/user/dto/CustomUserPrincipal.kt
  backend/src/main/java/com/coing/domain/user/dto/OAuth2UserDto.java
  backend/src/main/java/com/coing/domain/user/dto/OAuth2UserDto.kt
  backend/src/main/java/com/coing/domain/user/entity/Authority.java
  backend/src/main/java/com/coing/domain/user/entity/Authority.kt
  backend/src/main/java/com/coing/domain/user/entity/Provider.java
  backend/src/main/java/com/coing/domain/user/entity/Provider.kt
  backend/src/test/java/com/coing/domain/chat/controller/ChatControllerTest.kt
  backend/src/test/java/com/coing/domain/chat/service/ChatServiceTest.kt
  backend/src/test/java/com/coing/domain/coin/market/service/MarketServiceTest.kt
  backend/src/test/java/com/coing/domain/news/controller/NewsControllerTest.kt
  backend/src/test/java/com/coing/domain/news/service/NewsServiceTest.kt
Labels: BE, ✨ feature

#27 Feat/15 kotlin migration infra upbit package
  backend/build.gradle.kts
  backend/src/main/java/com/coing/domain/coin/ticker/service/TickerService.kt
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.kt
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketConnection.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketConnection.kt
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketService.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketService.kt
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitApiTradeDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketFormatDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketFormatDto.kt
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTicketDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTicketDto.kt
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTypeDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTypeDto.kt
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitRequestType.java
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitRequestType.kt
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitWebSocketFormat.java
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitWebSocketFormat.kt
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitWebSocketType.java
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitWebSocketType.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketHandler.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketHandler.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandler.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandler.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTickerHandler.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTickerHandler.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTradeHandler.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTradeHandler.kt
  backend/src/main/java/com/coing/infra/upbit/util/UpbitRequestBuilder.java
  backend/src/main/java/com/coing/infra/upbit/util/UpbitRequestBuilder.kt
  backend/src/test/java/com/coing/infra/upbit/UpbitConnectionIntegrationTest.java
  backend/src/test/java/com/coing/infra/upbit/UpbitConnectionIntegrationTest.kt
  backend/src/test/java/com/coing/infra/upbit/adapter/UpbitWebSocketConnectionTest.java
  backend/src/test/java/com/coing/infra/upbit/adapter/UpbitWebSocketConnectionTest.kt
  backend/src/test/java/com/coing/infra/upbit/adapter/UpbitWebSocketServiceTest.java
  backend/src/test/java/com/coing/infra/upbit/adapter/UpbitWebSocketServiceTest.kt
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketHandlerTest.java
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketHandlerTest.kt
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandlerTest.java
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandlerTest.kt
Labels: BE, ♻️ refactor

#30 Feat/24 migrate global package
  backend/src/main/java/com/coing/global/config/AsyncConfig.java
  backend/src/main/java/com/coing/global/config/AsyncConfig.kt
  backend/src/main/java/com/coing/global/config/CacheConfig.java
  backend/src/main/java/com/coing/global/config/CacheConfig.kt
  backend/src/main/java/com/coing/global/config/ChatCacheConfig.java
  backend/src/main/java/com/coing/global/config/ChatCacheConfig.kt
  backend/src/main/java/com/coing/global/config/JacksonConfig.java
  backend/src/main/java/com/coing/global/config/JacksonConfig.kt
  backend/src/main/java/com/coing/global/config/MailConfig.java
  backend/src/main/java/com/coing/global/config/MailConfig.kt
  backend/src/main/java/com/coing/global/config/MessageConfig.java
  backend/src/main/java/com/coing/global/config/MessageConfig.kt
  backend/src/main/java/com/coing/global/config/RestTemplateConfig.java
  backend/src/main/java/com/coing/global/config/RestTemplateConfig.kt
  backend/src/main/java/com/coing/global/config/SecurityConfig.java
  backend/src/main/java/com/coing/global/config/SecurityConfig.kt
  backend/src/main/java/com/coing/global/config/SpringDocConfig.java
  backend/src/main/java/com/coing/global/config/SpringDocConfig.kt
  backend/src/main/java/com/coing/global/config/WebSocketClientConfig.java
  backend/src/main/java/com/coing/global/config/WebSocketClientConfig.kt
  backend/src/main/java/com/coing/global/config/WebSocketConfig.java
  backend/src/main/java/com/coing/global/config/WebSocketConfig.kt
  backend/src/main/java/com/coing/global/exception/BusinessException.java
  backend/src/main/java/com/coing/global/exception/BusinessException.kt
  backend/src/main/java/com/coing/global/exception/RestExceptionHandler.java
  backend/src/main/java/com/coing/global/exception/RestExceptionHandler.kt
  backend/src/main/java/com/coing/global/exception/doc/ApiErrorCodeExamples.java
  backend/src/main/java/com/coing/global/exception/doc/ApiErrorCodeExamples.kt
  backend/src/main/java/com/coing/global/exception/doc/ErrorCode.kt
  backend/src/main/java/com/coing/global/exception/doc/ExampleHolder.java
  backend/src/main/java/com/coing/global/exception/doc/ExampleHolder.kt
  backend/src/main/java/com/coing/global/init/DevInitData.java
  backend/src/main/java/com/coing/global/init/DevInitData.kt
  backend/src/main/java/com/coing/global/security/CustomAuthenticationEntryPoint.java
  backend/src/main/java/com/coing/global/security/CustomAuthenticationEntryPoint.kt
  backend/src/main/java/com/coing/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/coing/global/security/filter/JwtAuthenticationFilter.kt
  backend/src/main/java/com/coing/global/security/handler/OAuth2LoginFailureHandler.java
  backend/src/main/java/com/coing/global/security/handler/OAuth2LoginFailureHandler.kt
  backend/src/main/java/com/coing/global/security/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/coing/global/security/handler/OAuth2LoginSuccessHandler.kt
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.kt
Labels: BE, ✨ feature

#28 refactor: update test annotations and improve error handling in user and candle services
  api_schema.json
  backend/src/main/java/com/coing/domain/coin/candle/service/UpbitCandleService.kt
  backend/src/main/java/com/coing/domain/news/service/NewsService.kt
  backend/src/main/java/com/coing/domain/user/controller/UserController.kt
  backend/src/main/java/com/coing/domain/user/service/OAuth2UserService.kt
  backend/src/main/resources/messages.properties
  backend/src/test/java/com/coing/domain/coin/candle/controller/CandleControllerTest.kt
  backend/src/test/java/com/coing/domain/news/controller/NewsControllerTest.kt
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.kt
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.kt
Labels: BE, ♻️ refactor

#32 Feat/31 migrate util package
  backend/src/main/java/com/coing/domain/chat/entity/ChatRoom.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatService.kt
  backend/src/main/java/com/coing/domain/user/email/service/EmailVerificationService.kt
  backend/src/main/java/com/coing/domain/user/email/service/PasswordResetService.kt
  backend/src/main/java/com/coing/util/BaseEntity.java
  backend/src/main/java/com/coing/util/BaseEntity.kt
  backend/src/main/java/com/coing/util/BasicResponse.java
  backend/src/main/java/com/coing/util/BasicResponse.kt
  backend/src/main/java/com/coing/util/LocalDateDeserializer.java
  backend/src/main/java/com/coing/util/LocalDateDeserializer.kt
  backend/src/main/java/com/coing/util/LocalTimeDeserializer.java
  backend/src/main/java/com/coing/util/LocalTimeDeserializer.kt
  backend/src/main/java/com/coing/util/MessageUtil.java
  backend/src/main/java/com/coing/util/MessageUtil.kt
  backend/src/main/java/com/coing/util/PageUtil.java
  backend/src/main/java/com/coing/util/PageUtil.kt
  backend/src/main/java/com/coing/util/Ut.java
  backend/src/main/java/com/coing/util/Ut.kt
  backend/src/test/java/com/coing/domain/chat/controller/ChatControllerTest.kt
  backend/src/test/java/com/coing/domain/chat/service/ChatServiceTest.kt
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.kt
  backend/src/test/java/com/coing/util/UtilTest.java
  backend/src/test/java/com/coing/util/UtilTest.kt
Labels: BE, ✨ feature

#45 Feat/38 refactor decouple upbit websocket
  backend/src/main/java/com/coing/domain/coin/common/port/DataHandler.kt
  backend/src/main/java/com/coing/domain/coin/orderbook/service/OrderbookService.kt
  backend/src/main/java/com/coing/domain/coin/ticker/service/TickerService.kt
  backend/src/main/java/com/coing/domain/coin/trade/service/TradeService.kt
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandler.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTickerHandler.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTradeHandler.kt
  backend/src/test/java/com/coing/domain/coin/orderbook/service/OrderbookServiceTest.kt
  backend/src/test/java/com/coing/domain/coin/ticker/service/TickerServiceTest.kt
  backend/src/test/java/com/coing/domain/coin/trade/service/TradeServiceTest.kt
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandlerTest.kt
Labels: BE, ♻️ refactor

#48 Feat/47 fix upbit websocket payload error
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.kt
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketConnection.kt
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTypeDto.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandler.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTickerHandler.kt
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTradeHandler.kt
  backend/src/main/java/com/coing/infra/upbit/util/UpbitRequestBuilder.kt
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandlerTest.kt
Labels: BE, ⛔️ bug

#49 Feat/41 chat report
  backend/src/main/java/com/coing/domain/bookmark/controller/BookmarkController.kt
  backend/src/main/java/com/coing/domain/chat/controller/ChatController.kt
  backend/src/main/java/com/coing/domain/chat/controller/ChatReportController.kt
  backend/src/main/java/com/coing/domain/chat/dto/ChatMessageReportDto.kt
  backend/src/main/java/com/coing/domain/chat/entity/ChatMessageReport.kt
  backend/src/main/java/com/coing/domain/chat/repository/ChatMessageReportRepository.kt
  backend/src/main/java/com/coing/domain/chat/repository/ChatMessageRepository.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatReportService.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatService.kt
  backend/src/main/java/com/coing/domain/coin/candle/controller/CandleController.kt
  backend/src/main/java/com/coing/domain/news/controller/NewsController.kt
  backend/src/main/java/com/coing/domain/user/controller/AdminController.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/UserResponse.kt
  backend/src/main/java/com/coing/domain/user/dto/CustomUserPrincipal.kt
  backend/src/main/java/com/coing/domain/user/entity/Authority.kt
  backend/src/main/java/com/coing/domain/user/entity/User.kt
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.kt
  backend/src/main/java/com/coing/global/config/SecurityConfig.kt
  backend/src/main/java/com/coing/global/exception/doc/ErrorCode.kt
  backend/src/main/java/com/coing/global/security/filter/JwtAuthenticationFilter.kt
  backend/src/test/java/com/coing/domain/bookmark/service/BookmarkServiceTest.kt
  backend/src/test/java/com/coing/domain/chat/controller/ChatControllerTest.kt
  backend/src/test/java/com/coing/domain/chat/controller/ChatReportControllerTest.kt
  backend/src/test/java/com/coing/domain/chat/service/ChatServiceTest.kt
  backend/src/test/java/com/coing/domain/user/controller/AdminControllerTest.kt
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.kt
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.kt
Labels: BE, ✨ feature

#51 Feat/43 external messaging dependency
  backend/src/main/java/com/coing/domain/coin/common/port/CodeDto.kt
  backend/src/main/java/com/coing/domain/coin/common/port/CoinDataHandler.kt
  backend/src/main/java/com/coing/domain/coin/common/port/EventPublisher.kt
  backend/src/main/java/com/coing/domain/coin/orderbook/dto/OrderbookDto.kt
  backend/src/main/java/com/coing/domain/coin/orderbook/service/OrderbookService.kt
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickerDto.kt
  backend/src/main/java/com/coing/domain/coin/ticker/service/TickerService.kt
  backend/src/main/java/com/coing/domain/coin/trade/dto/TradeDto.kt
  backend/src/main/java/com/coing/domain/coin/trade/service/TradeService.kt
  backend/src/main/java/com/coing/infra/messaging/websocket/WebSocketEventPublisherConfig.kt
  backend/src/main/java/com/coing/infra/messaging/websocket/constant/WebSocketSubscriptionTopics.kt
  backend/src/main/java/com/coing/infra/messaging/websocket/publisher/WebSocketEventPublisher.kt
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.kt
  backend/src/test/java/com/coing/domain/coin/orderbook/service/OrderbookServiceTest.kt
  backend/src/test/java/com/coing/domain/coin/ticker/service/TickerServiceTest.kt
  backend/src/test/java/com/coing/domain/coin/trade/service/TradeServiceTest.kt
Labels: BE, ♻️ refactor

#52 Feat/42 withdraw social login
  api_schema.json
  backend/src/main/java/com/coing/domain/coin/market/controller/MarketController.kt
  backend/src/main/java/com/coing/domain/user/controller/UserController.kt
  backend/src/main/java/com/coing/domain/user/service/UserService.kt
  backend/src/main/java/com/coing/global/config/SecurityConfig.kt
  backend/src/main/java/com/coing/global/security/handler/OAuth2LoginSuccessHandler.kt
  backend/src/main/java/com/coing/global/security/resolver/CustomAuthorizationRequestResolver.kt
  frontend/src/app/user/info/page.tsx
  frontend/src/app/user/social-login/redirect/page.tsx
Labels: BE, FE, ✨ feature

#54 Fix/53 add exception in redirectSocialQuit
  backend/src/main/java/com/coing/domain/user/controller/UserController.kt
Labels: BE, ⛔️ bug

#59 Feat/57 admin page
  api_schema.json
  backend/src/main/java/com/coing/domain/user/controller/AdminController.kt
  backend/src/test/java/com/coing/domain/user/controller/AdminControllerTest.kt
  frontend/package-lock.json
  frontend/src/app/admin/dashboard/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/store/user.store.ts
Labels: BE, FE, ✨ feature

#64 Feat/63 chat report modify
  backend/src/main/java/com/coing/domain/chat/controller/ChatController.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatHelperService.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatReportService.kt
  backend/src/main/java/com/coing/domain/chat/service/ChatService.kt
  frontend/src/app/admin/dashboard/page.tsx
Labels: BE, ⛔️ bug, FE

#73 feat: enhance chat input handling and message reporting
  frontend/src/app/coin/components/ChatPanel.tsx
Labels: ⛔️ bug, FE

#74 fix: move @Retry to fetchAndUpdateCoins method
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.kt
Labels: BE, ⛔️ bug

#81 Feat/77 separate quit
  backend/src/main/java/com/coing/domain/user/controller/UserController.kt
  backend/src/main/java/com/coing/domain/user/controller/dto/UserInfoResponse.kt
  backend/src/main/java/com/coing/domain/user/service/UserService.kt
  frontend/src/app/coin/components/ShareModal.tsx
  frontend/src/app/user/info/page.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/store/user.store.ts
Labels: FE, ✨ feature
